### ISSUE TITLE
小米11，安卓11版本，运行1.7.2脚本报错

### ISSUE THREAD

**Issue by CallMeHiker** [JavisPeng/taojinbi#116]
小米11，安卓11版本，运行1.7.2脚本报错

Thread[main (Spawn-0),5]: TypeError: Cannot call method "child" of null (/storage/emulated/0/脚本/tjb.js#107)
TypeError: Cannot call method "child" of null
    at get_task (/storage/emulated/0/脚本/tjb.js:107:0)
    at do_simple_task (/storage/emulated/0/脚本/tjb.js:449:0)
    at taojinbi_task (/storage/emulated/0/脚本/tjb.js:527:0)
    at main (/storage/emulated/0/脚本/tjb.js:571:0)
    at /storage/emulated/0/脚本/tjb.js:874:0

**Comment by Hadeslock** [comment]
在红米k20pro，安卓11上遇到相似错误

**Comment by JavisPeng** [comment]
淘宝列表更新了，版本请更新到1.7.3
