### ISSUE TITLE
1.7.2运行报错，三星s10+，安卓11

### ISSUE THREAD

**Issue by SunZongming** [JavisPeng/taojinbi#117]
/E: Thread[main (Spawn-1),5]: TypeError: Cannot call method "child" of null (/data/user/0/com.taojinbi486/files/project/taojinbi.js#107)
TypeError: Cannot call method "child" of null
    at get_task (/data/user/0/com.taojinbi486/files/project/taojinbi.js:107:0)
    at do_simple_task (/data/user/0/com.taojinbi486/files/project/taojinbi.js:449:0)
    at taojinbi_task (/data/user/0/com.taojinbi486/files/project/taojinbi.js:527:0)
    at main (/data/user/0/com.taojinbi486/files/project/taojinbi.js:571:0)
    at /data/user/0/com.taojinbi486/files/project/taojinbi.js:874:0

**Comment by ctt0124** [comment]
line107，去掉最后的 .child(0) 就可以了

**Comment by JavisPeng** [comment]
淘宝列表更新了，版本请更新到1.7.3
