### ISSUE TITLE
查看消消乐任务后报错

### ISSUE THREAD

**Issue by CNunicorn6** [JavisPeng/taojinbi#37]
日志
```
查看-蚂蚁庄园喂小鸡任务
查看-浇灌福气任务任务
去年货节浇灌福气（0/1）
查看-可执行的简单浏览任务
简单浏览任务执行完毕
查看-蚂蚁森林任务
蚂蚁四年了浇水或收能量（0/1）
查看-消消乐任务
查看-可执行的简单浏览任务
查看-蚂蚁森林任务
蚂蚁四年了浇水或收能量（0/1）
查看-消消乐任务
Thread[main (Spawn-0),5]: TypeError: Cannot call method "bounds" of null (/storage/emulated/0/脚本/taojinbi.js#646)
TypeError: Cannot call method "bounds" of null
    at water_fortune_task (/storage/emulated/0/脚本/taojinbi.js:646:0)
    at do_water_fortune_task (/storage/emulated/0/脚本/taojinbi.js:654:0)
    at taojinbi_task (/storage/emulated/0/脚本/taojinbi.js:482:0)
    at main (/storage/emulated/0/脚本/taojinbi.js:526:0)
    at /storage/emulated/0/脚本/taojinbi.js:781:0
```

**Comment by JavisPeng** [comment]
好的，下午修复一下

**Comment by JavisPeng** [comment]
新版已经修复
